apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-declarativo
spec:
  containers:
    - name: nginx-container
      image: nginx:stable
      resources:
        limits:
          cpu: "1"
          memory: "10Mi"