apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    name: pod-volume
spec:
  containers:
    - name: pod-volume-01
      image: nginx:latest
      resources:
        limits:
          cpu: "1"
          memory: "100Mi"
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/teste"
          name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: pvc-sample