apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-stable
spec:
  template:
    metadata:
      name: pod-1
      labels:
        app: deployment-canary
        track: stable
    spec:
      containers:
        - name: container-pod-1
          image: nginx:latest
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: deployment-canary